### ISSUE TITLE
Use Hashtag on instagram and twitter to compile images 

### ISSUE THREAD

**Issue by storycoder** [CodeForCharlotte/adopt-a-street#32]
I'd like adopt a thing to grab images posted on twitter and instagram every time an image is posted under a specific hashtag such as "#AdoptACLT" or something better. 

That way images can be repurposed for further use, perhaps even auto-posted on the website.

**Comment by derekrail89** [comment]
so there will need to be a screening process cause i can see that going the way of the #NYPDCares fiasco.

**Comment by storycoder** [comment]
makes sense. I don't know of the fiasco perse but i know the trolling a hashtag is a possibility.

**Comment by tannerhodges** [comment]
This is something we can circle back around to later. For now, marking as closed.
